export const MINIMUM_MESSAGE_LENGTH = 1;
export const MAXIMUM_MESSAGE_LENGTH = 1000;

export const ATTACHMENTS_ALLOWED_FILETYPE = "application/pdf";
export const ATTACHMENTS_FILESIZE_LIMIT_MB = 10;
export const ATTACHMENTS_FILESIZE_LIMIT =
  ATTACHMENTS_FILESIZE_LIMIT_MB * 1024 * 1024;
