services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        API_BASE_URL: http://backend:5000
    ports:
      - 3000:3000
    depends_on:
      - backend
    environment:
      - API_BASE_URL=http://backend:5000
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    ports:
      - 5000:5000
