MINIMUM_MESSAGE_LENGTH = 1
MAXIMUM_MESSAGE_LENGTH = 1000

FACT_CHECKING_SOURCES = [
    "https://craftinginterpreters.com/introduction.html",
    "https://craftinginterpreters.com/a-map-of-the-territory.html",
    "https://craftinginterpreters.com/the-lox-language.html",
    "https://craftinginterpreters.com/scanning.html",
    "https://craftinginterpreters.com/representing-code.html",
    "https://craftinginterpreters.com/parsing-expressions.html",
    "https://craftinginterpreters.com/evaluating-expressions.html",
    "https://craftinginterpreters.com/statements-and-state.html",
    "https://craftinginterpreters.com/control-flow.html",
    "https://craftinginterpreters.com/functions.html",
    "https://craftinginterpreters.com/resolving-and-binding.html",
    "https://craftinginterpreters.com/classes.html",
    "https://craftinginterpreters.com/inheritance.html",
    "https://craftinginterpreters.com/chunks-of-bytecode.html",
    "https://craftinginterpreters.com/a-virtual-machine.html",
    "https://craftinginterpreters.com/scanning-on-demand.html",
    "https://craftinginterpreters.com/compiling-expressions.html",
    "https://craftinginterpreters.com/types-of-values.html",
    "https://craftinginterpreters.com/strings.html",
    "https://craftinginterpreters.com/hash-tables.html",
    "https://craftinginterpreters.com/global-variables.html",
    "https://craftinginterpreters.com/local-variables.html",
    "https://craftinginterpreters.com/jumping-back-and-forth.html",
    "https://craftinginterpreters.com/calls-and-functions.html",
    "https://craftinginterpreters.com/closures.html",
    "https://craftinginterpreters.com/garbage-collection.html",
    "https://craftinginterpreters.com/classes-and-instances.html",
    "https://craftinginterpreters.com/methods-and-initializers.html",
    "https://craftinginterpreters.com/superclasses.html",
    "https://craftinginterpreters.com/optimization.html",
    "https://craftinginterpreters.com/appendix-i.html",
    "https://craftinginterpreters.com/appendix-ii.html",
]
